name = "hono-rpc-sample-backend"
compatibility_date = "2025-01-28"
compatibility_flags = [ "nodejs_compat" ]
main = "./src/presentations/index.ts"
preview_urls = false
workers_dev = false

[observability]
enabled = true

# local
[env.development.vars]
FRONTEND_URL = "http://localhost:3002"

[[env.development.d1_databases]]
binding = "D1"
database_name = "hono-rpc-sample-backend-db"
database_id = "f1f9bbae-f053-4de7-a05d-0462b76185fe"

# Cloudflare
[env.production.vars]
FRONTEND_URL = [
  "https://hono-rpc-sample.enchan.me",
  "https://master.hono-rpc-sample-frontend.pages.dev"
]

[[env.production.routes]]
pattern = "api.hono-rpc-sample.enchan.me"
custom_domain = true

[[env.production.d1_databases]]
binding = "D1"
database_name = "hono-rpc-sample-backend-db"
database_id = "f1f9bbae-f053-4de7-a05d-0462b76185fe"
