name = "hono-rpc-sample-backend"
compatibility_date = "2025-01-28"
compatibility_flags = [ "nodejs_compat" ]
main = "./src/presentations/index.ts"
preview_urls = false
workers_dev = false

[observability]
enabled = true

# development (ローカル)
[env.development.vars]
CORS_ALLOW_ORIGINS = "http://localhost:5173"
AUTH_DOMAIN = "enchan.jp.auth0.com"
AUTH_AUDIENCE = "http://localhost:8787"

[[env.development.d1_databases]]
binding = "D1"
migrations_dir = "./src/infrastructure/migrations"
database_name = "hono-rpc-sample-backend-db-dev"
database_id = "00000000-0000-0000-0000-000000000000"

# staging
[env.staging.vars]
CORS_ALLOW_ORIGINS = "https://master.hono-rpc-sample-frontend.pages.dev"
AUTH_DOMAIN = "enchan.jp.auth0.com"
AUTH_AUDIENCE = "https://stg.api.hono-rpc-sample.enchan.me"

[[env.staging.routes]]
pattern = "stg.api.hono-rpc-sample.enchan.me"
custom_domain = true

[[env.staging.d1_databases]]
binding = "D1"
migrations_dir = "./src/infrastructure/migrations"
database_name = "hono-rpc-sample-backend-db-stg"
database_id = "d5a98b37-9972-4458-8ea1-d8d8407dbc45"

# Cloudflare
[env.production.vars]
CORS_ALLOW_ORIGINS = "https://hono-rpc-sample.enchan.me"
AUTH_DOMAIN = "enchan.jp.auth0.com"
AUTH_AUDIENCE = "https://api.hono-rpc-sample.enchan.me"

[[env.production.routes]]
pattern = "api.hono-rpc-sample.enchan.me"
custom_domain = true

[[env.production.d1_databases]]
binding = "D1"
migrations_dir = "./src/infrastructure/migrations"
database_name = "hono-rpc-sample-backend-db-prod"
database_id = "ccd7a9d9-f393-4ffb-b481-b80951e24667"
