name: deploy
on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - release

jobs:
  deploy:
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      DEPLOY_ENV: ${{ github.ref == 'refs/heads/master' && 'staging' || github.ref == 'refs/heads/release' && 'production' || '' }}
      DEPLOY_ENV_SHORT: ${{ github.ref == 'refs/heads/master' && 'stg' || github.ref == 'refs/heads/release' && 'prod' || '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install
        run: npm i

      - name: test
        run: npm run -w backend test

      - name: deploy backend
        run: npm run -w backend deploy -- --env=${{ env.DEPLOY_ENV }}

      - name: apply D1 migration
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          environment: ${{ env.DEPLOY_ENV }}
          workingDirectory: backend
          command: d1 migrations apply --remote hono-rpc-sample-backend-db-${{ env.DEPLOY_ENV_SHORT }}

      - name: deploy frontend
        env:
          MODE: ${{ env.DEPLOY_ENV }}
        run: npm run -w frontend deploy
