name: deploy
on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - release

jobs:
  deploy:
    env:
      DEPLOY_ENV: ${{ github.ref == 'refs/heads/master' && 'staging' || github.ref == 'refs/heads/release' && 'production' || '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install
        run: npm i

      - name: deploy backend
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npm run -w backend deploy -- --env=${{ env.DEPLOY_ENV }}

      - name: deploy frontend
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          VITE_AUTH_CLIENT_ID: ${{ secrets.VITE_AUTH_CLIENT_ID }}
        run: npm run -w frontend deploy
