name: unit test (backend)
on:
  push:
    paths:
      - 'backend/**'
      - './package.json'
      - './eslint.config.mjs'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install
        run: npm i

      - name: configure environment
        run: cp backend/.dev.vars.sample backend/.dev.vars

      - name: test
        run: npm run -w backend test
